### ISSUE TITLE
Rename Render to Renderer

### ISSUE THREAD

**Issue by termhn** [rustgd/rendy#11]
It's two extra letters to type, but it makes it more obvious that this is a noun and not a verb. "Render" in english can't really become an object on its own, it is always an action. A Renderer would be a thing that performs rendering, which is more precisely what the type is. This would also affect RenderBuilder which would become RendererBuilder.

**Comment by torkleyy** [comment]
Hmm, but it's a trait we're talking about. I think the trait can be called `Render` and a struct implementing it would then be a renderer. Why does it need to be a noun? 😅

**Comment by minecrawler** [comment]
It's a little confusing imho, because you don't "build render" ;)

**Comment by torkleyy** [comment]
Makes sense..

**Comment by LucioFranco** [comment]
@termhn at least how I see it, the `Render` trait is fine, because you can implement `Render` for some type. Maybe, a better word would be `Renderable`?

**Comment by torkleyy** [comment]
I don't mind renaming. @omni-viral What do you think?

**Comment by termhn** [comment]
Perhaps `Runner` since its primary function is to `run` the passes that have been set up? Alternatively, I thought about `Engine`, since it's kind of the main driving force behind actually running things, but that seems a bit too abstract to me.

**Comment by omni-viral** [comment]
This entity doesn't exists anymore
